FILES = asynctest nbtest setconsole setlevel heartbeat mapper inp outp \
	datasize load50 netifdebug netifconfig

INCLUDEDIR = /usr/include
CFLAGS = -O2 -fomit-frame-pointer -Wall -I$(INCLUDEDIR)

all: $(FILES)

clean:
	rm -f $(FILES) *~ core
	
