#!/bin/sh
module="scullp"
device="scullp"
group="wheel"
mode="664"

# remove stale nodes
rm -f /dev/${device}? 

# invoke insmod with all arguments we got
/sbin/insmod -f $module $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0  /dev/${device}

# give appropriate group/permissions
chgrp $group /dev/${device}[0-3]
chmod $mode  /dev/${device}[0-3]
