#!/bin/sh
module="sbull"
device="sbull"
group="wheel"
mode="664"

# invoke insmod with all arguments we got
/sbin/insmod -f $module $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[0-3] /dev/${device}

mknod /dev/${device}0 b $major 0
mknod /dev/${device}1 b $major 1
mknod /dev/${device}2 b $major 2
mknod /dev/${device}3 b $major 3
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}[0-3] 
chmod $mode  /dev/${device}[0-3]






